package SixteenS::Statistics::ReadsSummary;
use strict;

##This pm is mainly to statistic the nubmer of reads generated by sequencing 
##and the number of tags after quality contrl steps such as BIPES and UCHIME
##

sub falist_readsnumber{
    ##This is only two arguments 
    ##The first is a file contain the list of all the target files, and
    ##the second is the output hash contain all the numbers
    my @tem = @_;
    
    die "Can not open $tem[0] or $tem[0] does not exist $!\n" unless(-e $tem[0]) && open(IN, "$tem[0]");
    while(<I>)
    {
        my $num = `grep ">" $_ -c`;
        my @te = split(/\//,$_);
        chomp($num);
        $$tem[1]{$te[-2]} = $num;
    }
    close I;
}#raw_readsnumber



1;
__END__
