package SixteenS::Statistics::TaxonDistribution;
use strict;

#--------------------------------------------------------
#Alpha-diversity indices were generated by these function
#--------------------------------------------------------
sub rarefacton_groups{
    ##this function is used to plot rarefaction curves
    ##we plot different groups with certain color
    ##Two arguements 1. rarefaction table 2. groups table


}##rarefaction_groups

sub alpha_indices{
    ##this funciotn is used to generate the alpha diversity
    ##indices table you must make sure that mothur be installed


}#alpha_indices

sub rank_abundance{


}#rank_abundance

sub taxon_distribution{
    ##this function is mainly for generation of the barchart plot 
    ##for the taxonomy distribution
    ##

}#taxon_distribution



1;
__END__
